### ISSUE TITLE
Melhorar README.md

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#101]
Baseado na atualização no repositório em inglês: https://github.com/railsgirls/railsgirls.github.io/pull/435

**Comment by JoaoAPS** [comment]
Olá, eu gostaria de trabalhar na issue.

Também percebi que no arquivo que é mudado o markdown não está exibindo o código YAML direito ([link](https://github.com/railsgirls/guides-ptbr/blob/main/_posts/2012-04-19-contributing.markdown#-highlight-yaml-)).
Posso corrigir isso também com base na versão em inglês, que usa `<dev></dev>` pra exibir o código ao invés de `{% highligh %}`, tudo bem?.

**Comment by anaschwendler** [comment]
Oi @JoaoAPS pode fazer sim, vou te atribuir a issue!

**Comment by JoaoAPS** [comment]
Pull request submetida #117

**Comment by anaschwendler** [comment]
Closed by #117
