### ISSUE TITLE
Melhorar explicação de terminal de comando

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#102]
Baseado na atualização no repositório em inglês: https://github.com/railsgirls/railsgirls.github.io/pull/436

**Comment by JoaoAPS** [comment]
Acho que essa issue já foi resolvida pelo commit 43ca73ffd50d19467b4b71f560c8ccf32d485fbf.

**Comment by anaschwendler** [comment]
Verdade @JoaoAPS eu acho que fiz algumas issues um tempo atrás, mas devem existir algumas mudanças pra aumentar a legibilidade, mas sim, você tá certo!
