### ISSUE TITLE
Atualizar processo para instalar yarn (necessário para Rails 6.0.0)

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#105]
Baseado na atualização no repositório em inglês: https://github.com/railsgirls/railsgirls.github.io/pull/427

**Comment by thaisfalbo** [comment]
Olá, posso fazer esta issue?

**Comment by anaschwendler** [comment]
Oi @thaisfalbo tudo bom?

Por mim pode pegar sim, mas eu não sei se primeiro eu não acharia melhor fazer #100 que pensa?

**Comment by thaisfalbo** [comment]
Oi @anaschwendler, vou fazer o #100 primeiro então.

**Comment by anaschwendler** [comment]
Closed by #106
