### ISSUE TITLE
Adicionar tutorial de Shoulda Matchers

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#46]
Um tutorial da gem Shoulda Matchers foi adicionado: http://guides.railsgirls.com/testing-shoulda-matchers

Markdown: https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2017-08-13-shoulda-matchers.markdown

Para adicionar:
- Adicionar link a página inicial
- Criar um novo arquivo para o post 

🎉

**Comment by frankyston** [comment]
Pull Request do novo post feito https://github.com/railsgirls/guides-ptbr/pull/57.

**Comment by anaschwendler** [comment]
muito obrigada!!
