### ISSUE TITLE
Adicionar tutorial de Passenger 

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#47]
Um tutorial da gem Passenger foi adicionado: http://guides.railsgirls.com/passenger

Markdown: https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2018-02-01-passenger.markdown

Para adicionar:

- Adicionar link a página inicial
- Criar um novo arquivo para o post

🎉

**Comment by frankyston** [comment]
Vou fazer a tradução deste tutorial.

**Comment by frankyston** [comment]
Pull Request do post do Passenger: https://github.com/railsgirls/guides-ptbr/pull/58

**Comment by anaschwendler** [comment]
Valeu @frankyston !
