### ISSUE TITLE
Atualizar README 

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#60]
Algo necessário pro futuro:
0. Como forkar o projeto
1. Como rodar o projeto
2. Como abrir PR
3. Adicionar regras de tradução

Discussão sobre terminologia: https://github.com/railsgirls/guides-ptbr/issues/24

Decisões:

- Tudo o que não for palavra reservada (e.g. variáveis, nomes de classes), traduzir para o português;
- As referências a `COACH` serão traduzidos como `INSTRUTOR(A)`;
- Se existir algum problema de clareza e compreensão a cerca do que está na versão original, corrigir no momento da tradução (é legal abrir um PR no guia em EN pra corrigir lá também);

**Comment by frankyston** [comment]
@anaschwendler segue o Pull Request da issue https://github.com/railsgirls/guides-ptbr/pull/62

**Comment by anaschwendler** [comment]
Fechou, mais uma parte resolvida @frankyston muito obrigada por toda ajuda até aqui, tá sendo essencial pra fazer o guides voltar a ativa de novo :)

**Comment by anaschwendler** [comment]
@frankyston agora vi que nem precisava ter adicionado mais info no seu PR, você adicionou tudo, que perfeito!

**Comment by frankyston** [comment]
> Fechou, mais uma parte resolvida @frankyston muito obrigada por toda ajuda até aqui, tá sendo essencial pra fazer o guides voltar a ativa de novo :)

eu que agradeço, está sendo muito legal poder contribuir 😄
