### ISSUE TITLE
Trocar em todos os arquivos Coach para Instrutor(a)

### ISSUE THREAD

**Issue by frankyston** [railsgirls/guides-ptbr#63]
Foi decidido que na tradução do Inglês para Português a palavra `Coach` deve ser trocado para `Instrutor(a)`

**Comment by frankyston** [comment]
@anaschwendler verifiquei que muitos arquivos a tradução está como `Coach`, posso realizar essa troca nos arquivos traduzidos?

**Comment by anaschwendler** [comment]
Oi @frankyston, claro que pode!
Eu ia fazer isso em algum momento no futuro, mas se não for problema para você, eu acharia ótimo!

Eu gostaria de fazer essa conferência e mais outras:
- Tem alguns estilos de markdown (e sintaxe) faltando em algumas páginas
- A checagem de palavras (não tanto as traduções, mas mais as decisões mesmo - tipo coach)

Se não for muito trabalhoso e você puder ajudar (até parcialmente) já ajuda bastante! :)

**Comment by frankyston** [comment]
legal @anaschwendler podemos fazer isso gradualmente, primeiro trocamos o `Coach` e quando for decidido as outras mudanças criamos mais issues para realizar essas mudanças.

Estarei fazendo essa semana mesmo a checagem geral do `Coach`.

**Comment by frankyston** [comment]
Pull Request para a tradução `Coach`: https://github.com/railsgirls/guides-ptbr/pull/65

@anaschwendler teria como exemplificar os estilos de markwdown faltando nas páginas para poder fazer essa verificação?

**Comment by anaschwendler** [comment]
Valeu @frankyston !!

> @anaschwendler teria como exemplificar os estilos de markwdown faltando nas páginas para poder fazer essa verificação?

Eu não sei muito bem como fazer essa verificação, mas eu lembro que ano passado enquanto fazendo algumas traduções eu vi bastantes estilos faltando, tipo só o `{ highlight }` mesmo tava faltando em alguns lugares, mas esse dá pra ir arrumando conforme o tempo passar :)

**Comment by frankyston** [comment]
@anaschwendler vou fechar essa isseue e abrir uma nova só para verificar os highlights.
