### ISSUE TITLE
Adicionar First Timers Only tag

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#67]
Esse projeto é bem simples de receber contribuição, acho que chegamos ao ponto em que podemos adicionar a tag de first timers only agora: https://www.firsttimersonly.com/

**Comment by carolcodes** [comment]
só colocar no README mesmo? eu posso cuidar disso

**Comment by anaschwendler** [comment]
Oi @carolcodes, é isso aí mesmo 😅 
Eu adicionei essa issue pra trazer mais pessoas pra contribuir mesmo :)
Então, mesmo pequena, é uma contribuição haha!

**Comment by RafaelaMachado** [comment]
Oi meninas, já que está um tempo parado aqui,  adicionei o badge e abri um PRzinho

**Comment by anaschwendler** [comment]
Oi @RafaelaMachado !
Muito obrigada, vou te atribuir a issue e aceitar teu PR :)
