### ISSUE TITLE
Adicionar passenger tutorial

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#70]
Esse post de 2018 ainda não foi incluído aos tutoriais em português

Arquivo em inglês: http://guides.railsgirls.com/passenger
Arquivo em português: adicionar a posts com o nome `2018-02-01-passenger.markdown`
Post no github: https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2018-02-01-passenger.markdown

**Comment by giovana-morais** [comment]
posso me encarregar desse? :shipit:

**Comment by anaschwendler** [comment]
Bem vinda @giovana-morais !

Claro que pode, se você se sente confortável pra fazer, pode assumir sim, vou atribuir a issue pra ti.

**Comment by giovana-morais** [comment]
@anaschwendler fui dar uma olhada agora e fazer a tradução e notei que o arquivo do passenger [já está traduzido](https://github.com/railsgirls/guides-ptbr/blob/master/_posts/2018-02-01-passenger.markdown)! hahaha

**Comment by anaschwendler** [comment]
@giovana-morais  Ohhh! Falha minha!!! Mas eu devo pegar os que faltam em breve tem mais 4 que falta traduzir e alguns pra revisar (atulizar e tal).
Eu tenho a lista:
2014-05-29-touristic-autism_continuous-deployment.markdown
2014-05-29-touristic-autism_resource-modeling.markdown
2014-05-29-touristic-autism_design.markdown
2015-09-11-continuous-snap-ci.markdown

Me falta abrir as issues direitinho 😅

**Comment by giovana-morais** [comment]
@anaschwendler quer que eu abra as issues desses que estão faltando? aí posso pegar um pra ir traduzindo, os outros ficam em aberto e cê pode focar em achar esses que precisam de revisão.

**Comment by giovana-morais** [comment]
bom, acho que consegui abrir todas as issues

2014-05-29-touristic-autism_continuous-deployment.markdown -- Issue #72 
2014-05-29-touristic-autism_resource-modeling.markdown -- Issue #71 
2014-05-29-touristic-autism_design.markdown -- Issue #74 
2015-09-11-continuous-snap-ci.markdown -- Issue #73 

falta adicionar os labels de "good first issue" e "hacktoberfest", mas isso eu não consigo fazer. se quiser me colocar na #73  eu vou fazendo durante a semana (:

**Comment by anaschwendler** [comment]
@giovana-morais Nossa!!! Muito obrigada por toda essa mão!
Essa semana tem bastante coisa acontecendo, então não to conseguindo arrumar as issues, mas muito obrigada, pode ir fazendo no teu tempo sem problema, se tu tá com tempo, pra mim é ótimo!

Vou adicionar as labels ali, e ver o que falta.

E claro, te adicionar ao #73!
