### ISSUE TITLE
Adicionar Resource Modeling tutorial

### ISSUE THREAD

**Issue by giovana-morais** [railsgirls/guides-ptbr#71]
É necessário incluir esse post de 2014 aos tutoriais em português

Arquivo em inglês: https://guides.railsgirls.com/touristic-autism_resource-modeling

Arquivo em português: adicionar a `_posts/` com o nome `2014-05-29-touristic-autism_resource-modeling.markdown`

Post no github: https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2014-05-29-touristic-autism_resource-modeling.markdown

**Comment by elaine-quinto** [comment]
Olá, posso traduzir este? :eyes:

**Comment by elainemattos** [comment]
Olá, posso traduzir este? :eyes:

**Comment by anaschwendler** [comment]
Bem-vinda @elainemattos !

Claro! Se tu se sentir confortável pra fazer, pode traduzir sim, já vou atribuir a issue pro teu user! o/

**Comment by anaschwendler** [comment]
Oi @elainemattos alguma novidade no post?

**Comment by elainemattos** [comment]
Oi @anaschwendler! estou traduzindo, amanhã no máximo já abro PR :)

**Comment by anaschwendler** [comment]
Muito obrigada @elainemattos <3

Só queria conferir se tava tudo bem :)

**Comment by anaschwendler** [comment]
Closed by #86
