### ISSUE TITLE
Adicionar Continuous Deployment tutorial 

### ISSUE THREAD

**Issue by giovana-morais** [railsgirls/guides-ptbr#72]
Esse post ainda não foi incluído aos tutoriais em português

Arquivo em inglês: https://guides.railsgirls.com/touristic-autism_continuous-deployment

Arquivo em português: adicionar a `_posts/` com o nome `2014-05-29-touristic-autism_continuous-deployment.markdown`

Post no github: https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2014-05-29-touristic-autism_continuous-deployment.markdown

**Comment by mathesouza** [comment]
Bom dia!
Gostaria de contribuir com essa issue, tudo bem?

**Comment by giovana-morais** [comment]
perfeito, faça no seu tempo. (:  

@anaschwendler você pode colocar o @rmuliterno na issue, por gentileza?

**Comment by anaschwendler** [comment]
Oi @giovana-morais e @rmuliterno!

Já estou atribuindo a issue, em breve devo abrir mais issues pra esse mês, vou dedicar minha noite pra isso :)

**Comment by anaschwendler** [comment]
Closed by #77
