### ISSUE TITLE
Adicionar Continuos Deployment with Snap CI

### ISSUE THREAD

**Issue by giovana-morais** [railsgirls/guides-ptbr#73]
Post no site: https://guides.railsgirls.com/continuous-snap-ci

Salvar o arquivo no diretório `_posts/` com o nome `2015-09-11-continuous-snap-ci.markdown`

Post no GitHub: https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2015-09-11-continuous-snap-ci.markdown

**Comment by rmuliterno** [comment]
Olá! Posso traduzir esse post pra vocês!

**Comment by giovana-morais** [comment]
oi @rmuliterno eu já traduzi esse! vou fazer o PR hoje à noite. (:

 contudo acredito que ainda há tutoriais disponíveis, como a issue  #72 . se você tiver interesse, fique à vontade pra contribuir!

**Comment by anaschwendler** [comment]
Closed by #75
