### ISSUE TITLE
Adicionar Design tutorial

### ISSUE THREAD

**Issue by giovana-morais** [railsgirls/guides-ptbr#74]
Post no site (inglês): https://guides.railsgirls.com/touristic-autism_design

Post no GitHub: https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2014-05-29-touristic-autism_design.markdown

Salvar arquivo no diretório `_posts/` com o nome `2014-05-29-touristic-autism_design.markdown`

**Comment by thaisfalbo** [comment]
Olá, já estou traduzindo este post.

**Comment by anaschwendler** [comment]
Oi @thaisfalbo, bem-vinda 🎉 

Já atribui a você, muito obrigada por traduzir!

**Comment by anaschwendler** [comment]
Closed by #76
