### ISSUE TITLE
Tradução 2015-08-16-sinatra-app-tutorial-in-bulgarian.markdown

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#80]
Esse post ainda não foi incluído aos tutoriais em português

Arquivo em inglês: https://guides.railsgirls.com/sinatra-app-bg
Post no github: https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2015-08-16-sinatra-app-tutorial-in-bulgarian.markdown

Arquivo para tradução em português: `_posts/2015-08-16-sinatra-app-tutorial-in-bulgarian.markdown`

PS: Esse é nível 2, tem um título em círilico, vai envolver usar translate haha

**Comment by thaisfalbo** [comment]
Posso fazer essa tradução?

**Comment by anaschwendler** [comment]
Oi @thaisfalbo 
Ah, ok, eu não tinha visto isso, queres pegar o de shoula matchers?
