### ISSUE TITLE
Adicionar outros guias para todos os tutoriais

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#89]
Como aberto [aqui](https://github.com/railsgirls/railsgirls.github.io/pull/418), achei uma ótima contribuição e acho que precisamos replicar na nossa versão também :)

**Comment by lmmc2** [comment]
Olá! Se ainda estiver aberto gostaria de fazer.

**Comment by RafaelaMachado** [comment]
Oi meninas, como está essa issue?
Ela ainda é válida? Posso puxar?

**Comment by anaschwendler** [comment]
Oi @RafaelaMachado eu não recebi o PR para essa issue, se for confortável para você, com certeza pode puxar, será sempre bem-vindo! 💯 

Vou te marcar na issue e pode continuar :)
