### ISSUE TITLE
Arrumar URL para o git cheat sheet

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#91]
Como [nessa atualização](https://github.com/railsgirls/railsgirls.github.io/pull/413/files) no repositório em inglês, precisamos refletir no nosso repositório em português.

**Comment by andressavldrs** [comment]
Posso resolver essa issue?

**Comment by anaschwendler** [comment]
Claro @andressavldrs vou te atribuir a issue 🎉

**Comment by anaschwendler** [comment]
Closed by #93
