### ISSUE TITLE
Removi código demais do tutorial de RSpec

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#92]
¯\_(ツ)_/¯ 

Arrumei [aqui](https://github.com/railsgirls/railsgirls.github.io/pull/423)

Fica aberto para arrumar no tutorial PT/BR

**Comment by thaisfalbo** [comment]
Já estou fazendo essa issue

**Comment by anaschwendler** [comment]
Te atribui a issue @thaisfalbo

**Comment by anaschwendler** [comment]
Closed by #97

**Comment by anaschwendler** [comment]
Closed by #97
