### ISSUE TITLE
Atualizar para nova marca da Apple (MacOS)

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/guides-ptbr#98]
Refletindo as mudanças do PR: https://github.com/railsgirls/railsgirls.github.io/pull/424 no nosso projeto

**Comment by tuannyruiz** [comment]
Eu posso fazer esse :)

**Comment by anaschwendler** [comment]
Beleza @tuannyruiz !

Vou te atribuir a issue então 🎉 
Happy hacking! 👩‍💻

**Comment by tuannyruiz** [comment]
Oi, @anaschwendler, eu finalizei essa tarefa, quando puder dá uma olhada :)
Valeu!

**Comment by anaschwendler** [comment]
Oi @tuannyruiz !!

Eu vi que o PR foi aberto, só não consegui revisar ainda 😅 peço perdão, devo ter tempo hoje a noite! o/

**Comment by anaschwendler** [comment]
Closed by #99
